############
# TEST IMAGE
############

FROM cypress/base

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install

COPY . ./

COPY entrypoint.sh /usr/bin

RUN chmod 755 /usr/bin/entrypoint.sh

ENTRYPOINT ["sh", "/usr/bin/entrypoint.sh"]

CMD sleep 30 && yarn test
